
services:
  postgres:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

  redis:
    image: redis:7.4.3
    container_name: redis
    ports:
      - "6380:6379"
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"   # MinIO server
      - "9001:9001"   # MinIO console (web UI)
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/library
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    restart: unless-stopped

volumes:
  db:
  minio-data:

