spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/library
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000
  minio:
    url: http://minio:9000
    access-key: root
    secret-key: password
    bucket: mybucket

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.data.redis: DEBUG

server:
  port: 8080
debug: true
