spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/library
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6380   # <== because redis in Docker is mapped 6380:6379 for local
      timeout: 2000
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.data.redis: DEBUG
server:
  port: 8080
debug: true
