spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
  paths-to-match: /**
#  packages-to-scan: com.library.library.controller

axon:
  axonserver:
    servers: localhost:8124

logging:
  level:
    org.hibernate.SQL: debug  # Only show when debug is enabled
    org.hibernate.type: warn