spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
#    default-schema: liquibase_db
  #    properties:
#      hibernate:
#        format_sql: true

  #  security:
#    oauth2:
#      resource server:
#        jwt:
#          audiences:



management:
  endpoints:
    web:
      exposure:
        include: health , info, mappings, beans
  info:
    env:
      enabled: true
#logging:
#  level:
#    root: info
#    org:
#      springframework: info
#      hibernate: debug
server:
  port: 8080
debug: true


