spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/library
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000
#camunda:
#  client:
#    zeebe:
#      base-url: zeebe :26500
#      grpc-address: zb://zeebe:26500
#      rest-address: http://127.0.0.1:8080

#camunda:
#  client:
#    mode: self-managed
#    zeebe:
#      enabled: true
#      grpc-address: http://127.0.0.1:26500
#      rest-address: http://127.0.0.1:8080
camunda:
  client:
    mode: self-managed
    zeebe:
      enabled: true
      # Remove space in base-url and use correct protocol
#      base-url: http://zeebe:8080
#      grpc-address: zeebe:26500
      grpc-address: zeebe:26500
      # Use zeebe container name instead of localhost
#      rest-address: http://zeebe:8080
      rest-address: http://127.0.0.1:8080
#      execution-threads: 2



logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.data.redis: DEBUG
server:
  port: 8080
debug: true
