spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/library
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000
#camunda:
#  client:
#    zeebe:
#      base-url: zeebe :26500
#      grpc-address: zb://zeebe:26500
#      rest-address: http://127.0.0.1:8080

#camunda:
#  client:
#    mode: self-managed
#    zeebe:
#      enabled: true
#      grpc-address: http://127.0.0.1:26500
#      rest-address: http://127.0.0.1:8080
camunda:
  client:
    mode: self-managed
    zeebe:
      enabled: true
      # Remove space in base-url and use correct protocol
#      base-url: http://zeebe:8080
#      grpc-address: zeebe:26500
      grpc-address: http://127.0.0.1:26500
      # Use zeebe container name instead of localhost
#      rest-address: http://zeebe:8080
      rest-address: http://127.0.0.1:8080
      # Authentication configuration to match docker-compose
#      auth:
#        client-id: ${ZEEBE_CLIENT_ID}
#        client-secret: ${ZEEBE_CLIENT_SECRET}
#        token-url: http://keycloak:18080/auth/realms/camunda-platform/protocol/openid-connect/token
#        audience: zeebe-api
#        credentials-cache-path: /tmp/zeebe_auth_cache

#identity:
#  base-url: http://identity:8084
#  issuer-url: http://keycloak:18080/auth/realms/camunda-platform


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.data.redis: DEBUG
server:
  port: 8080
debug: true
